### ISSUE TITLE
Looking for someone to change my params.

### ISSUE THREAD

**Issue by mzaboss** [transitive-bullshit/snapchat#24]
Hello,

I just hooked an jailbroken device, and I extracted the Tokens.

However, I managed to use addfriend endpoint. and works perfectly.

But I tried to send a snap with failed attempt. sounds my image doesn't upload to snapchat servers for some reasons.

I need somebody to fix the params. Its a NodeJS script.

code: https://gist.github.com/mzaboss/9d4be77151eb7f366d6d69f0aacbb479

If you can help me am willing to pay good. Skype: mzaboss

Thank you,
regards.

**Comment by fisch0920** [comment]
@mzaboss the link you posted gives a 404. Are you sure it's a public gist?

**Comment by mzaboss** [comment]
@fisch0920 hey, anything new buddy? I just want the /loq/send params/headers.

**Comment by VirenMohindra** [comment]
Gist has once again been deleted, can't help you out with params if we can't see the code
